version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: nextjs-fullstack-db
    environment:
      POSTGRES_DB: nextjs_fullstack_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d nextjs_fullstack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build: .
    container_name: nextjs-fullstack-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@postgres:5432/nextjs_fullstack_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-production-nextauth-secret-change-this
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
