version: "3.8"

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:16-alpine
    container_name: express-fullstack-db-dev
    environment:
      POSTGRES_DB: express_fullstack_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d express_fullstack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Development (optional)
  redis:
    image: redis:7-alpine
    container_name: express-fullstack-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
  redis_dev_data:
