name: Project Automation

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  pull_request:
    types:
      [opened, edited, closed, reopened, ready_for_review, converted_to_draft]
  pull_request_review:
    types: [submitted]

jobs:
  issue-automation:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Add to project board
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Sehnya/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-assign labels based on title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const labels = [];

            // Auto-assign labels based on title patterns
            if (title.includes('[bug]') || title.includes('bug:')) {
              labels.push('bug');
            }
            if (title.includes('[feature]') || title.includes('feature:')) {
              labels.push('enhancement');
            }
            if (title.includes('[template]') || title.includes('template:')) {
              labels.push('template');
            }
            if (title.includes('[version]') || title.includes('version:')) {
              labels.push('version-update');
            }
            if (title.includes('security') || title.includes('vulnerability')) {
              labels.push('security');
            }
            if (title.includes('documentation') || title.includes('docs')) {
              labels.push('documentation');
            }

            // Add priority labels based on keywords
            if (title.includes('critical') || title.includes('urgent')) {
              labels.push('priority:high');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }

      - name: Welcome new contributors
        uses: actions/github-script@v7
        if: github.event.action == 'opened'
        with:
          script: |
            // Check if this is the user's first issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.payload.issue.user.login,
              state: 'all'
            });

            if (issues.data.length === 1) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `👋 Welcome to Peezy CLI! Thanks for opening your first issue.
                
                A maintainer will review this issue soon. In the meantime:
                - Make sure you've provided all the requested information
                - Check out our [Contributing Guide](https://github.com/Sehnya/peezy-cli/blob/main/CONTRIBUTING.md)
                - Join our community discussions
                
                We appreciate your contribution to making Peezy CLI better! 🚀`
              });
            }

  pr-automation:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_review'
    steps:
      - name: Add PR to project board
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Sehnya/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-assign labels to PR
        uses: actions/github-script@v7
        if: github.event.action == 'opened'
        with:
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const body = context.payload.pull_request.body || '';
            const labels = [];

            // Auto-assign labels based on PR title and content
            if (title.includes('fix') || title.includes('bug')) {
              labels.push('bug');
            }
            if (title.includes('feat') || title.includes('feature') || title.includes('add')) {
              labels.push('enhancement');
            }
            if (title.includes('docs') || title.includes('documentation')) {
              labels.push('documentation');
            }
            if (title.includes('test') || title.includes('testing')) {
              labels.push('testing');
            }
            if (title.includes('refactor') || title.includes('cleanup')) {
              labels.push('refactoring');
            }
            if (title.includes('security')) {
              labels.push('security');
            }
            if (title.includes('template')) {
              labels.push('template');
            }
            if (title.includes('version') || title.includes('update') || title.includes('upgrade')) {
              labels.push('version-update');
            }

            // Check for breaking changes
            if (body.includes('breaking change') || body.includes('BREAKING CHANGE')) {
              labels.push('breaking-change');
            }

            // Check if it's a draft
            if (context.payload.pull_request.draft) {
              labels.push('work-in-progress');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }

      - name: Request review from maintainers
        uses: actions/github-script@v7
        if: github.event.action == 'ready_for_review' || (github.event.action == 'opened' && !github.event.pull_request.draft)
        with:
          script: |
            // Request review from maintainers
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_request_number: context.payload.pull_request.number,
              reviewers: ['Sehnya'] // Add other maintainers as needed
            });

      - name: Thank contributor on merge
        uses: actions/github-script@v7
        if: github.event.action == 'closed' && github.event.pull_request.merged
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🎉 Thank you for your contribution! Your changes have been merged and will be included in the next release.
              
              If this was your first contribution, welcome to the Peezy CLI community! 🚀
              
              Keep an eye out for the next release where your changes will be available to all users.`
            });

  stale-issue-management:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Mark stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. 
            It will be closed if no further activity occurs within 7 days.

            If this issue is still relevant, please:
            - Add a comment to keep it open
            - Provide additional information if requested
            - Update the issue description if needed

            Thank you for your contributions to Peezy CLI! 🚀
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs within 7 days.

            If you're still working on this PR, please:
            - Add a comment to keep it open
            - Push new commits to update it
            - Resolve any merge conflicts

            Thank you for your contributions to Peezy CLI! 🚀
          close-issue-message: |
            This issue was automatically closed due to inactivity.

            If you believe this issue is still relevant, please reopen it with updated information.
          close-pr-message: |
            This pull request was automatically closed due to inactivity.

            If you'd like to continue working on this, please reopen it or create a new PR.
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: "pinned,security,critical,good first issue"
          exempt-pr-labels: "pinned,security,critical"
